version: "3.7"
services:
    # image project
    laravel_8:
        build: 
            args: 
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - laravel-eti
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8080:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-eti

    # db mysql
    postgresql:
        image: postgres:10
        restart: unless-stopped
        volumes:
            - ./.docker/postgress/pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - laravel-eti
        env_file: .env
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_DATABASE

    # queue
    queue:
        build: 
            args: 
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        networks: 
            - laravel-eti

networks: 
    laravel-eti:
        driver: bridge